[WIP] Added mark/reset functionality to BufferInputStream.
apple/servicetalk pull request #2447
Opened 2022-11-28 23:49 UTC by bobbyowolabi

Motivation:
BufferInputStream can support the mark/reset functionality, as noted in #1562, like ByteArrayInputStream and ByteBufInputStream (from netty).

Modifications:
- Implemented the mark, reset and markSupported methods of BufferInputStream
- Added test cases

Result:
Addresses #1562

2022-11-30 19:02 UTC, idelpivnitskiy requested changes
Thanks for the contribution @bobbyowolabi!

2022-12-01 00:01 UTC, bobbyowolabi commented on servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferInputStream.java
> +    public synchronized void mark(final int readlimit) {
Good point, removed `synchronized` from both mark and reset methods .

2022-12-01 00:03 UTC, bobbyowolabi commented on servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferInputStream.java
> +            throw new IOException("the number of bytes read from the stream since mark was last called is larger " +
I agree, it didn't feel necessary when writing it, I just put what I saw in `InputStream.java`.
I removed these checks and followed the impl in `ByteArrayInputStream`.

2022-12-01 00:04 UTC, bobbyowolabi commented on servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferInputStream.java
> +    private int markpos = -1;
I like that, very clean.
Updated, thanks.

2022-12-01 00:05 UTC, bobbyowolabi commented on servicetalk-buffer-api/src/main/java/io/servicetalk/buffer/api/BufferInputStream.java
> +            throw new IOException("mark has not been called since the stream was created");
👍🏾
Updated.

2022-12-01 00:06 UTC, bobbyowolabi commented on servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/BufferInputStreamTest.java
> +        skipFully(initialSkipCount, is);
Good Point, updated to `readBytes`/`skipBytes`.

2022-12-01 00:07 UTC, bobbyowolabi commented
Thank you for your time to review and all the feedback.

2022-12-01 22:27 UTC, bobbyowolabi commented on servicetalk-buffer-api/src/test/java/io/servicetalk/buffer/api/BufferInputStreamTest.java
> +    private void skipFully(final long n, final InputStream inputStream) throws IOException {
Updated both the `skipBytes` and `readBytes` methods to be static.

2022-12-02 19:43 UTC, idelpivnitskiy approved these changes
Looks sparkling clean now. Thanks for the contribution, @bobbyowolabi!

2022-12-02 19:43 UTC, merged