Deprecate ConnectionAcceptor(+ Factory) "append"
apple/servicetalk pull request #2479
Opened 2023-01-02 16:07 UTC by daschl

Motivation:

At the moment the user experience on how to apply multiple ConnectionAcceptorFactories is confusing because there are many different ways on how to perform this task.

In order to improve the ambiguity there should only be one common way to append multiple acceptor factories.

Modifications:

This changeset deprecates the append methods on both the ConnectionAcceptor and the ConnectionAcceptorFactory. A new ConnectionAcceptorFactoryAppender is added which is used internally and in tests, but can be used by a user who needs to port functionality forward when relying on the old behavior.

All internal use of the deprecated APIs has been replaced with the helper class in preparation for later removal.

Result:

The primary API to chain the acceptors should be through the regular HttpServerBuilder which is now expressed through deprecation and later removal of the other APIs.

2023-01-04 07:43 UTC, idelpivnitskiy requested changes

2023-01-04 07:43 UTC, idelpivnitskiy commented on servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionAcceptorFactoryAppender.java
> +public final class ConnectionAcceptorFactoryAppender implements ConnectionAcceptorFactory {
By exposing a new public class we don't reduce number of ways how to append ConnectionAcceptorFactories. The expectation was that `HttpServerBuilder#appendConnectionAcceptorFilter(ConnectionAcceptorFactory)` will be the only way to append acceptors, working in a way similar to `appendServiceFilter`

2023-01-06 00:56 UTC, idelpivnitskiy commented
Let's finish with an early connection acceptor before proceeding with this PR. Maybe we won't need to make any changes here if we come up with new interfaces and deprecate `ConnectionAcceptor`

2023-01-16 08:06 UTC, daschl commented
Will abandon this one for a new one which just deprecates on top of the new early and late acceptors.

2023-01-16 08:06 UTC, closed without merging